### ISSUE TITLE
Accepted flow

### ISSUE THREAD

**Issue by ezhao** [contactpush/contact#11]
- [x] create dialog fragment when the request is clicked allowing the user to view user requesting to connect and either accept or decline
- [x] implement logic behind the accept or decline actions. Tell Parse
- [x] Parse pushes a notification to the user
- [x] refresh contacts fragment on accept

Extended in #38

**Comment by ekilah** [comment]
working on logic to accept/decline and reporting to parse. updated steps for this part

**Comment by ekilah** [comment]
can now accept/deny/revoke requests. parse is updated.

**Comment by ekilah** [comment]
@rtteal added the photo of the fromUser to the dialog, a bit of progress here

**Comment by ezhao** [comment]
moving nice-to-haves to separate issue and closing this one
