### ISSUE TITLE
Data schema

### ISSUE THREAD

**Issue by ezhao** [contactpush/contact#12]
Ideas here
https://github.com/contactpush/contact/wiki
- [ ] figure out relational data model in Parse to have generic data fields & decide if we should do it
- [ ] do it if so

**Comment by ekilah** [comment]
Basics for Request (formerly Connection), ContactInfo, and User are up in Parse

**Comment by rtteal** [comment]
@ezhao I've been making some progress on this.  Let me know if you want to chat about this.

**Comment by ezhao** [comment]
@rtteal what did you decide to do?

**Comment by rtteal** [comment]
See updated [schema.](https://github.com/contactpush/contact/wiki)
