### ISSUE TITLE
Set up Parse Cloud Code

### ISSUE THREAD

**Issue by ezhao** [contactpush/contact#14]
Set up Parse Cloud Code. Doing this so we can do push notifications properly. It'll be a separate repo because it's technically server-side stuff.

**Comment by ezhao** [comment]
@rtteal actually I think you already set this up. is it committed somewhere? does parse handle that automatically?

**Comment by rtteal** [comment]
I downloaded the sample code and played with it a bit. I haven't made much progress with this piece.  What do you mean by, "does parse handle that automatically"?

**Comment by ezhao** [comment]
Googled around and I don't think Parse handles it (was hoping for a "parse pull" command or something)
Ok maybe we can just pull down from here - https://github.com/contactpush/ContactCloud
just committed the boilerplate stuff
