### ISSUE TITLE
Initial wireframes

### ISSUE THREAD

**Issue by ezhao** [contactpush/contact#2]
- [ ] Invite a bunch of your contacts to use the app
- [ ] Widget ("in event" story)
- [ ] Creating different profiles for different audiences
- [ ] View Profiles (distinguish between native Android content and our app's content)

**Comment by ezhao** [comment]
@rtteal @ekilah what's the best way to publish our wireframes before class today? should we use the wiki? do you have the html file hosted somewhere already? we'll need to link to it from our readme or an issue I think.

**Comment by rtteal** [comment]
@ezhao @ekilah I put a link to the wireframes at the bottom of our readme.  The repo for the wireframes is: https://github.com/contactpush/contactpush.github.io.  I uploaded the latest Pencil project to dropbox.  If you want to make any changes, export from Pencil to HTML, then do a find and replace for `%5C` with `/`.  You may also want to put `<!DOCTYPE html>` at the top of the file.  Once you push, the changes should automatically be visible here: http://contactpush.github.io./.

**Comment by ezhao** [comment]
Do you think we're ready to create an issue and cc the codepath aliases?

**Comment by rtteal** [comment]
I vote yes. What do y'all think?

**Comment by ekilah** [comment]
fine by me.
