### ISSUE TITLE
Clicking a contact no longer shows details

### ISSUE THREAD

**Issue by rtteal** [contactpush/contact#28]
When clicking a contact from the contacts list, it no longer shows the contact's details.  Issue is in CreateProfileFragment.
/cc @ekilah @ezhao

**Comment by ekilah** [comment]
Yep, looking into that right now.

On Sun, Mar 15, 2015 at 9:03 PM, Taylor Teal notifications@github.com
wrote:

> When clicking a contact from the contacts list, it no longer shows the
> contact's details. Issue is in CreateProfileFragment.
> /cc @ekilah https://github.com/ekilah @ezhao https://github.com/ezhao
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/contactpush/contact/issues/28.

## 

-Monroe Ekilah
http://www.linkedin.com/pub/monroe-ekilah/81/a55/20a/

**Comment by ekilah** [comment]
It's because the objectId passed to ContactInfo.getContactInfo is for the
contactInfo object, not the User. Looking into best solution right now.

On Sun, Mar 15, 2015 at 9:08 PM, Monroe Ekilah monroe.ekilah@gmail.com
wrote:

> Yep, looking into that right now.
> 
> On Sun, Mar 15, 2015 at 9:03 PM, Taylor Teal notifications@github.com
> wrote:
> 
> > When clicking a contact from the contacts list, it no longer shows the
> > contact's details. Issue is in CreateProfileFragment.
> > /cc @ekilah https://github.com/ekilah @ezhao https://github.com/ezhao
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/contactpush/contact/issues/28.
> 
> ## 
> 
> -Monroe Ekilah
> http://www.linkedin.com/pub/monroe-ekilah/81/a55/20a/

## 

-Monroe Ekilah
http://www.linkedin.com/pub/monroe-ekilah/81/a55/20a/

**Comment by ekilah** [comment]
The ContactInfo model doesn't successfully store the userId or a pointer to
the User object, which stores the location... any ideas?

On Sun, Mar 15, 2015 at 9:10 PM, Monroe Ekilah monroe.ekilah@gmail.com
wrote:

> It's because the objectId passed to ContactInfo.getContactInfo is for the
> contactInfo object, not the User. Looking into best solution right now.
> 
> On Sun, Mar 15, 2015 at 9:08 PM, Monroe Ekilah monroe.ekilah@gmail.com
> wrote:
> 
> > Yep, looking into that right now.
> > 
> > On Sun, Mar 15, 2015 at 9:03 PM, Taylor Teal notifications@github.com
> > wrote:
> > 
> > > When clicking a contact from the contacts list, it no longer shows the
> > > contact's details. Issue is in CreateProfileFragment.
> > > /cc @ekilah https://github.com/ekilah @ezhao
> > > https://github.com/ezhao
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/contactpush/contact/issues/28.
> > 
> > ## 
> > 
> > -Monroe Ekilah
> > http://www.linkedin.com/pub/monroe-ekilah/81/a55/20a/
> 
> ## 
> 
> -Monroe Ekilah
> http://www.linkedin.com/pub/monroe-ekilah/81/a55/20a/

## 

-Monroe Ekilah
http://www.linkedin.com/pub/monroe-ekilah/81/a55/20a/

**Comment by rtteal** [comment]
Why not store the geo loc in ContactInfo? Each user has a pointer to their own ContactInfo.

**Comment by ekilah** [comment]
could refactor to be there later, but I guess I didn't consider it a piece of ContactInfo earlier. seemed like the logical place to put it.

1d3244c fixes this.
