### ISSUE TITLE
Push causes black screen on startup

### ISSUE THREAD

**Issue by rtteal** [contactpush/contact#30]
Attempting to run the app with the push code in AndroidManifest not commented out and the GoogleApplication.subscribeToPush() uncommented causes my app not to start with the following log messages:

03-16 14:38:40.216    2084-2084/com.codepath.contact D/CrashReporting﹕ Crash reporting is enabled for com.codepath.contact, initializing...
03-16 14:38:40.220    2084-2084/com.codepath.contact D/CrashReporting﹕ Looking for error files in /data/data/com.codepath.contact/files/com.parse/cr/reports
03-16 14:38:40.220    2084-2084/com.codepath.contact D/CrashReporting﹕ Looking for error files in /data/data/com.codepath.contact/files/com.parse/cr/minidumps
03-16 14:38:40.260    2084-2216/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 1191K, 23% free 4468K/5792K, paused 6ms, total 6ms
03-16 14:38:40.284    2084-2084/com.codepath.contact D/WelcomeFragment﹕ Found user/pw from shared prefs. usr: test2, pw: test
03-16 14:39:45.556    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 73K, 4% free 3451K/3576K, paused 3ms, total 8ms
03-16 14:39:45.568    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 27K, 3% free 3908K/4000K, paused 3ms, total 3ms
03-16 14:39:45.568    2296-2296/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat21$SharedElementCallbackImpl; (55)
03-16 14:39:45.568    2296-2296/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/app/ActivityCompat21$SharedElementCallbackImpl;' failed
03-16 14:39:45.580    2296-2296/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/app/FragmentTransitionCompat21$1; (1388)
03-16 14:39:45.580    2296-2296/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/app/FragmentTransitionCompat21$1;' failed
03-16 14:39:45.580    2296-2296/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/app/FragmentTransitionCompat21$3; (1388)
03-16 14:39:45.584    2296-2296/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/app/FragmentTransitionCompat21$3;' failed
03-16 14:39:45.608    2296-2296/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/media/VolumeProviderCompatApi21$1; (188)
03-16 14:39:45.608    2296-2296/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/media/VolumeProviderCompatApi21$1;' failed
03-16 14:39:45.612    2296-2296/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/media/session/MediaControllerCompatApi21$CallbackProxy; (189)
03-16 14:39:45.612    2296-2296/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/media/session/MediaControllerCompatApi21$CallbackProxy;' failed
03-16 14:39:45.620    2296-2296/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/media/session/MediaSessionCompatApi21$CallbackProxy; (193)
03-16 14:39:45.624    2296-2296/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/media/session/MediaSessionCompatApi21$CallbackProxy;' failed
03-16 14:39:45.644    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 432K, 11% free 3988K/4472K, paused 6ms, total 6ms
03-16 14:39:45.644    2296-2296/com.codepath.contact I/dalvikvm﹕ Failed resolving Landroid/support/v4/view/ViewCompatApi21$1; interface 1440 'Landroid/view/View$OnApplyWindowInsetsListener;'
03-16 14:39:45.644    2296-2296/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/view/ViewCompatApi21$1;' failed
03-16 14:39:45.652    2296-2296/com.codepath.contact I/dalvikvm﹕ Failed resolving Landroid/support/v4/widget/DrawerLayoutCompatApi21$InsetsListener; interface 1440 'Landroid/view/View$OnApplyWindowInsetsListener;'
03-16 14:39:45.652    2296-2296/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/widget/DrawerLayoutCompatApi21$InsetsListener;' failed
03-16 14:39:45.664    2296-2296/com.codepath.contact W/dalvikvm﹕ method Landroid/support/v7/internal/widget/ListViewCompat;.lookForSelectablePosition incorrectly overrides package-private method with same name in Landroid/widget/ListView;
03-16 14:39:45.676    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 421K, 11% free 4079K/4552K, paused 3ms, total 3ms
03-16 14:39:45.728    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 399K, 10% free 4193K/4644K, paused 4ms, total 4ms
03-16 14:39:45.768    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 433K, 11% free 4271K/4756K, paused 3ms, total 3ms
03-16 14:39:45.820    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 427K, 10% free 4357K/4836K, paused 4ms, total 4ms
03-16 14:39:45.932    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 436K, 10% free 4436K/4924K, paused 11ms, total 11ms
03-16 14:39:45.952    2296-2296/com.codepath.contact I/dalvikvm﹕ Failed resolving Lcom/parse/FacebookAuthenticationProvider$1; interface 1809 'Lcom/facebook/android/Facebook$ServiceListener;'
03-16 14:39:45.952    2296-2296/com.codepath.contact W/dalvikvm﹕ Link of class 'Lcom/parse/FacebookAuthenticationProvider$1;' failed
03-16 14:39:45.956    2296-2296/com.codepath.contact I/dalvikvm﹕ Failed resolving Lcom/parse/FacebookAuthenticationProvider$2$1; interface 1797 'Lcom/facebook/Request$Callback;'
03-16 14:39:45.956    2296-2296/com.codepath.contact W/dalvikvm﹕ Link of class 'Lcom/parse/FacebookAuthenticationProvider$2$1;' failed
03-16 14:39:45.956    2296-2296/com.codepath.contact I/dalvikvm﹕ Failed resolving Lcom/parse/FacebookAuthenticationProvider$2; interface 1803 'Lcom/facebook/Session$StatusCallback;'
03-16 14:39:45.956    2296-2296/com.codepath.contact W/dalvikvm﹕ Link of class 'Lcom/parse/FacebookAuthenticationProvider$2;' failed
03-16 14:39:45.992    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 423K, 10% free 4525K/5000K, paused 3ms, total 3ms
03-16 14:39:46.040    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 433K, 10% free 4603K/5088K, paused 2ms, total 2ms
03-16 14:39:46.056    2296-2296/com.codepath.contact D/dalvikvm﹕ Note: class Lcom/google/android/gms/games/internal/IGamesService$Stub; has 195 unimplemented (abstract) methods
03-16 14:39:46.072    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 453K, 10% free 4683K/5188K, paused 3ms, total 3ms
03-16 14:39:46.108    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 475K, 10% free 4769K/5296K, paused 2ms, total 2ms
03-16 14:39:46.136    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 499K, 11% free 4862K/5412K, paused 2ms, total 2ms
03-16 14:39:46.168    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 530K, 11% free 4950K/5532K, paused 2ms, total 2ms
03-16 14:39:46.204    2296-2296/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 552K, 11% free 5048K/5652K, paused 3ms, total 3ms
03-16 14:39:46.224    2296-2296/com.codepath.contact D/CrashReporting﹕ Crash reporting is enabled for com.codepath.contact, initializing...
03-16 14:39:46.228    2296-2296/com.codepath.contact D/CrashReporting﹕ Looking for error files in /data/data/com.codepath.contact/files/com.parse/cr/reports
03-16 14:39:46.228    2296-2296/com.codepath.contact D/CrashReporting﹕ Looking for error files in /data/data/com.codepath.contact/files/com.parse/cr/minidumps
03-16 14:39:46.264    2296-2316/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 1370K, 25% free 4358K/5780K, paused 4ms, total 4ms

**Comment by ezhao** [comment]
just to clarify, @rtteal are you able to run the app if subscribeToPush() is commented out (i.e. all the permissions are intact in the manifest)

**Comment by rtteal** [comment]
No, it still black screens.  These are the logs I get when subscribeToPush() is commented out but the manifest is not:

03-16 15:28:06.232    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 50K, 3% free 3474K/3580K, paused 6ms, total 7ms
03-16 15:28:06.252    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 40K, 3% free 3914K/4028K, paused 3ms, total 4ms
03-16 15:28:06.260    2063-2063/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat21$SharedElementCallbackImpl; (55)
03-16 15:28:06.260    2063-2063/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/app/ActivityCompat21$SharedElementCallbackImpl;' failed
03-16 15:28:06.264    2063-2063/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/app/FragmentTransitionCompat21$1; (1388)
03-16 15:28:06.268    2063-2063/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/app/FragmentTransitionCompat21$1;' failed
03-16 15:28:06.272    2063-2063/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/app/FragmentTransitionCompat21$3; (1388)
03-16 15:28:06.272    2063-2063/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/app/FragmentTransitionCompat21$3;' failed
03-16 15:28:06.276    2063-2063/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/media/VolumeProviderCompatApi21$1; (188)
03-16 15:28:06.276    2063-2063/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/media/VolumeProviderCompatApi21$1;' failed
03-16 15:28:06.276    2063-2063/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/media/session/MediaControllerCompatApi21$CallbackProxy; (189)
03-16 15:28:06.280    2063-2063/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/media/session/MediaControllerCompatApi21$CallbackProxy;' failed
03-16 15:28:06.280    2063-2063/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/media/session/MediaSessionCompatApi21$CallbackProxy; (193)
03-16 15:28:06.280    2063-2063/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/media/session/MediaSessionCompatApi21$CallbackProxy;' failed
03-16 15:28:06.296    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 437K, 11% free 3991K/4484K, paused 2ms, total 2ms
03-16 15:28:06.304    2063-2063/com.codepath.contact I/dalvikvm﹕ Failed resolving Landroid/support/v4/view/ViewCompatApi21$1; interface 1440 'Landroid/view/View$OnApplyWindowInsetsListener;'
03-16 15:28:06.304    2063-2063/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/view/ViewCompatApi21$1;' failed
03-16 15:28:06.308    2063-2063/com.codepath.contact I/dalvikvm﹕ Failed resolving Landroid/support/v4/widget/DrawerLayoutCompatApi21$InsetsListener; interface 1440 'Landroid/view/View$OnApplyWindowInsetsListener;'
03-16 15:28:06.308    2063-2063/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/widget/DrawerLayoutCompatApi21$InsetsListener;' failed
03-16 15:28:06.336    2063-2063/com.codepath.contact W/dalvikvm﹕ method Landroid/support/v7/internal/widget/ListViewCompat;.lookForSelectablePosition incorrectly overrides package-private method with same name in Landroid/widget/ListView;
03-16 15:28:06.364    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 422K, 11% free 4082K/4560K, paused 9ms, total 9ms
03-16 15:28:06.428    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 399K, 10% free 4197K/4652K, paused 6ms, total 6ms
03-16 15:28:06.476    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 434K, 11% free 4274K/4764K, paused 3ms, total 3ms
03-16 15:28:06.524    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 427K, 10% free 4361K/4844K, paused 4ms, total 4ms
03-16 15:28:06.600    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 432K, 10% free 4440K/4928K, paused 15ms, total 15ms
03-16 15:28:06.620    2063-2063/com.codepath.contact I/dalvikvm﹕ Failed resolving Lcom/parse/FacebookAuthenticationProvider$1; interface 1809 'Lcom/facebook/android/Facebook$ServiceListener;'
03-16 15:28:06.620    2063-2063/com.codepath.contact W/dalvikvm﹕ Link of class 'Lcom/parse/FacebookAuthenticationProvider$1;' failed
03-16 15:28:06.620    2063-2063/com.codepath.contact I/dalvikvm﹕ Failed resolving Lcom/parse/FacebookAuthenticationProvider$2$1; interface 1797 'Lcom/facebook/Request$Callback;'
03-16 15:28:06.620    2063-2063/com.codepath.contact W/dalvikvm﹕ Link of class 'Lcom/parse/FacebookAuthenticationProvider$2$1;' failed
03-16 15:28:06.620    2063-2063/com.codepath.contact I/dalvikvm﹕ Failed resolving Lcom/parse/FacebookAuthenticationProvider$2; interface 1803 'Lcom/facebook/Session$StatusCallback;'
03-16 15:28:06.620    2063-2063/com.codepath.contact W/dalvikvm﹕ Link of class 'Lcom/parse/FacebookAuthenticationProvider$2;' failed
03-16 15:28:06.656    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 424K, 10% free 4528K/5008K, paused 4ms, total 4ms
03-16 15:28:06.704    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 435K, 10% free 4605K/5096K, paused 8ms, total 8ms
03-16 15:28:06.724    2063-2063/com.codepath.contact D/dalvikvm﹕ Note: class Lcom/google/android/gms/games/internal/IGamesService$Stub; has 195 unimplemented (abstract) methods
03-16 15:28:06.744    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 454K, 10% free 4685K/5196K, paused 3ms, total 3ms
03-16 15:28:06.784    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 475K, 11% free 4773K/5304K, paused 3ms, total 3ms
03-16 15:28:06.824    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 499K, 11% free 4865K/5420K, paused 6ms, total 6ms
03-16 15:28:06.884    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 533K, 11% free 4954K/5544K, paused 4ms, total 4ms
03-16 15:28:06.916    2063-2063/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 552K, 11% free 5051K/5660K, paused 2ms, total 2ms
03-16 15:28:06.940    2063-2063/com.codepath.contact D/CrashReporting﹕ Crash reporting is enabled for com.codepath.contact, initializing...
03-16 15:28:06.940    2063-2063/com.codepath.contact D/CrashReporting﹕ Looking for error files in /data/data/com.codepath.contact/files/com.parse/cr/reports
03-16 15:28:06.940    2063-2063/com.codepath.contact D/CrashReporting﹕ Looking for error files in /data/data/com.codepath.contact/files/com.parse/cr/minidumps
03-16 15:28:06.964    2063-2084/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 1259K, 23% free 4454K/5776K, paused 5ms, total 5ms
03-16 15:28:06.964    2063-2063/com.codepath.contact D/WelcomeFragment﹕ Found user/pw from shared prefs. usr: test2, pw: test
03-16 15:28:12.036    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 62K, 4% free 3462K/3580K, paused 3ms, total 3ms
03-16 15:28:12.052    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 40K, 3% free 3914K/4028K, paused 7ms, total 7ms
03-16 15:28:12.064    2422-2422/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/app/ActivityCompat21$SharedElementCallbackImpl; (55)
03-16 15:28:12.064    2422-2422/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/app/ActivityCompat21$SharedElementCallbackImpl;' failed
03-16 15:28:12.068    2422-2422/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/app/FragmentTransitionCompat21$1; (1388)
03-16 15:28:12.068    2422-2422/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/app/FragmentTransitionCompat21$1;' failed
03-16 15:28:12.068    2422-2422/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/app/FragmentTransitionCompat21$3; (1388)
03-16 15:28:12.068    2422-2422/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/app/FragmentTransitionCompat21$3;' failed
03-16 15:28:12.084    2422-2422/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/media/VolumeProviderCompatApi21$1; (188)
03-16 15:28:12.084    2422-2422/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/media/VolumeProviderCompatApi21$1;' failed
03-16 15:28:12.088    2422-2422/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/media/session/MediaControllerCompatApi21$CallbackProxy; (189)
03-16 15:28:12.088    2422-2422/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/media/session/MediaControllerCompatApi21$CallbackProxy;' failed
03-16 15:28:12.088    2422-2422/com.codepath.contact W/dalvikvm﹕ Unable to resolve superclass of Landroid/support/v4/media/session/MediaSessionCompatApi21$CallbackProxy; (193)
03-16 15:28:12.088    2422-2422/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/media/session/MediaSessionCompatApi21$CallbackProxy;' failed
03-16 15:28:12.120    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 437K, 11% free 3991K/4484K, paused 2ms, total 2ms
03-16 15:28:12.124    2422-2422/com.codepath.contact I/dalvikvm﹕ Failed resolving Landroid/support/v4/view/ViewCompatApi21$1; interface 1440 'Landroid/view/View$OnApplyWindowInsetsListener;'
03-16 15:28:12.124    2422-2422/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/view/ViewCompatApi21$1;' failed
03-16 15:28:12.124    2422-2422/com.codepath.contact I/dalvikvm﹕ Failed resolving Landroid/support/v4/widget/DrawerLayoutCompatApi21$InsetsListener; interface 1440 'Landroid/view/View$OnApplyWindowInsetsListener;'
03-16 15:28:12.124    2422-2422/com.codepath.contact W/dalvikvm﹕ Link of class 'Landroid/support/v4/widget/DrawerLayoutCompatApi21$InsetsListener;' failed
03-16 15:28:12.148    2422-2422/com.codepath.contact W/dalvikvm﹕ method Landroid/support/v7/internal/widget/ListViewCompat;.lookForSelectablePosition incorrectly overrides package-private method with same name in Landroid/widget/ListView;
03-16 15:28:12.156    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 422K, 11% free 4082K/4560K, paused 4ms, total 4ms
03-16 15:28:12.208    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 399K, 10% free 4197K/4652K, paused 4ms, total 4ms
03-16 15:28:12.244    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 434K, 11% free 4274K/4764K, paused 3ms, total 3ms
03-16 15:28:12.280    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 427K, 10% free 4361K/4844K, paused 3ms, total 3ms
03-16 15:28:12.320    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 431K, 10% free 4440K/4928K, paused 6ms, total 6ms
03-16 15:28:12.332    2422-2422/com.codepath.contact I/dalvikvm﹕ Failed resolving Lcom/parse/FacebookAuthenticationProvider$1; interface 1809 'Lcom/facebook/android/Facebook$ServiceListener;'
03-16 15:28:12.332    2422-2422/com.codepath.contact W/dalvikvm﹕ Link of class 'Lcom/parse/FacebookAuthenticationProvider$1;' failed
03-16 15:28:12.332    2422-2422/com.codepath.contact I/dalvikvm﹕ Failed resolving Lcom/parse/FacebookAuthenticationProvider$2$1; interface 1797 'Lcom/facebook/Request$Callback;'
03-16 15:28:12.332    2422-2422/com.codepath.contact W/dalvikvm﹕ Link of class 'Lcom/parse/FacebookAuthenticationProvider$2$1;' failed
03-16 15:28:12.332    2422-2422/com.codepath.contact I/dalvikvm﹕ Failed resolving Lcom/parse/FacebookAuthenticationProvider$2; interface 1803 'Lcom/facebook/Session$StatusCallback;'
03-16 15:28:12.332    2422-2422/com.codepath.contact W/dalvikvm﹕ Link of class 'Lcom/parse/FacebookAuthenticationProvider$2;' failed
03-16 15:28:12.364    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 424K, 10% free 4528K/5008K, paused 4ms, total 4ms
03-16 15:28:12.400    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 434K, 10% free 4606K/5096K, paused 5ms, total 5ms
03-16 15:28:12.416    2422-2422/com.codepath.contact D/dalvikvm﹕ Note: class Lcom/google/android/gms/games/internal/IGamesService$Stub; has 195 unimplemented (abstract) methods
03-16 15:28:12.436    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 454K, 10% free 4685K/5196K, paused 3ms, total 3ms
03-16 15:28:12.476    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 475K, 10% free 4773K/5304K, paused 4ms, total 4ms
03-16 15:28:12.500    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 499K, 11% free 4865K/5420K, paused 2ms, total 2ms
03-16 15:28:12.516    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 533K, 11% free 4955K/5544K, paused 3ms, total 3ms
03-16 15:28:12.548    2422-2422/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 556K, 11% free 5052K/5664K, paused 3ms, total 3ms
03-16 15:28:12.560    2422-2422/com.codepath.contact D/CrashReporting﹕ Crash reporting is enabled for com.codepath.contact, initializing...
03-16 15:28:12.572    2422-2422/com.codepath.contact D/CrashReporting﹕ Looking for error files in /data/data/com.codepath.contact/files/com.parse/cr/reports
03-16 15:28:12.572    2422-2422/com.codepath.contact D/CrashReporting﹕ Looking for error files in /data/data/com.codepath.contact/files/com.parse/cr/minidumps
03-16 15:28:12.576    2422-2443/com.codepath.contact D/dalvikvm﹕ GC_FOR_ALLOC freed 1204K, 24% free 4396K/5776K, paused 2ms, total 2ms
03-16 15:28:12.588    2422-2422/com.codepath.contact D/WelcomeFragment﹕ Found user/pw from shared prefs. usr: test2, pw: test

**Comment by rtteal** [comment]
Creating a new device seems to have resolved this issue.
