### ISSUE TITLE
Duplicates created in Sent list

### ISSUE THREAD

**Issue by rtteal** [contactpush/contact#32]
When sending a request, the sent list gets the request added twice.

**Comment by rtteal** [comment]
This is low priority, but I think we need to refactor the way this works.  I commented out the piece that I think we should get rid of and put comments in the code about this issue.  See [this](https://github.com/contactpush/contact/commit/d7369e7bbbcbd33c14a4b2461a2cf3f414549b18) for the changes made.

**Comment by ekilah** [comment]
That makes sense, on a good connection the request fragment will refresh itself I guess? That code was just like our Twitter client where we wanted the tweet to show immediately.

We don't need it I guess, but better would be to have the list check for dupes...

**Note**: in the commit you linked to, you commented out some things and deleted others, so the commented code won't function if/when uncommented

**Comment by rtteal** [comment]
Well I can certainly see why you would think I deleted some stuff based on the way the commit looks in the link above, but if you look closely, I was just moving some lines around, everything is still there.

**Comment by ekilah** [comment]
Ok cool yeah just took a quick peek at work.
- Monroe Ekilah
