### ISSUE TITLE
ProfileFragment

### ISSUE THREAD

**Issue by ezhao** [contactpush/contact#4]
Parent of "Create Profile" and "View Profile" fragments, so some amount of EditText/TextView swappability.
- [x] Create all the fields
- [x] Sync User object and Data objects to Parse

![](http://contactpush.github.io./pages/create_profile.png)
![](http://contactpush.github.io./pages/landing.png)

**Comment by rtteal** [comment]
I'm going to get started on the view.  Feel free to jump on the model/Parse piece if you want.

**Comment by rtteal** [comment]
Starting to work on the model/Parse piece for the Create Profile view now.  @ezhao let me know if you're already working on this.
