### ISSUE TITLE
LoginFragment with Google Auth

### ISSUE THREAD

**Issue by ezhao** [contactpush/contact#5]
Allow you to
- [x] Create account with user name and password
- [x] Create Parse account with user name and password
- [x] Prompt user with AccountPicker asking them which Google account they want to use
- [x] Request read/write access to user's Google Contacts and acquire Google Auth token

![](http://contactpush.github.io./pages/login_create_profile.png)

**Comment by ezhao** [comment]
hey @rtteal should we close this one?

**Comment by rtteal** [comment]
No, I updated this to reflect the pieces remaining.
