### ISSUE TITLE
AddUserFragment

### ISSUE THREAD

**Issue by ezhao** [contactpush/contact#6]
- [x] New activity and fragment for adding user
- [x] success or failure messaging (in new fragment?)
- [x] Creates Connection object in Parse

**Comment by ekilah** [comment]
@rtteal has a Request object instead of Connection, but it's the same thing it looks like.

**Comment by rtteal** [comment]
Yeah, I think a "Request" can turn into a "Connection" by flipping the "approved" column to true.
